refactor:1.17 Учебный проект: начинаем программировать.
htmlacademy-javascript/224592-code-and-magick-21 pull request #2
Opened 2020-09-27 23:37 UTC by AVBanin

2020-09-28 11:37 UTC, markovalenko requested changes

2020-09-28 11:37 UTC, markovalenko commented on index.html
> +  var getWizardX = function (FieldSizeX) {
```suggestion
  var getWizardX = function (fieldSizeX) {
```
Согласно требования интенсива, необходимо называть переменные со строчной буквы.

От себя могу добавить, что ожидаю имя класса, когда виду наименование переменной с заглавной буквы.

2020-09-28 13:03 UTC, AVBanin commented on index.html
> +  var getWizardX = function (FieldSizeX) {
Принято.
Ещё не прочёл критерии, но задача стоит.

Где прочитать про классы?

2020-09-29 05:33 UTC, markovalenko commented on index.html
> +  var getWizardX = function (FieldSizeX) {
Классы - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes. 
Скорее всего, пока рано в них углубляться, но общее представление не помешает. 
В текущем интенсиве мы не будем их использовать.

2020-09-30 06:34 UTC, merged